### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by schildbach** [ibauersachs/dnssecjava#1]
I see this project is already in use by other projects/libraries. It would be nice to release a first version so stable dependencies can be maintained.

**Comment by ibauersachs** [comment]
Which projects and libraries do you refer to?

I haven't released 1.0 yet because I wanted to finish the unit tests for the NSEC3 validation first. Also Verisign wanted to contribute a more formal set of validation tests, but unfortunately I haven't heard from them in a while.

**Comment by techguy613** [comment]
Hey Ingo! I know this fell off the map a bit, but I'm still trying to get ahold of a contact at Verisign to see where there are in the process. I'm hoping I can get a response sometime shortly :smile: 

Also, I have a library that uses dnssecjava. :+1:

**Comment by schildbach** [comment]
@ibauersachs Ingo, it's great to hear dnssecjava will get a comprehensive suite of unit tests! However if it's not clear when they will be finished, maybe you could consider releasing a version 0.9?

I was mostly referring to Matt's project, which I evaluate to use in [my project](https://github.com/schildbach/bitcoin-wallet) so I'd be a user of your library too.

**Comment by ibauersachs** [comment]
@schildbach Matt and I will do a little chat on Thursday, 25th Feb, 19:30 CET/UTC+1 at https://meet.jit.si/dnssecjava. Feel free to join us.

**Comment by ibauersachs** [comment]
Chat conclusion:
- Based on Matt's experience with the lib at Netki and the port to NodeJS it is stable enough for a release.
- I'll release 1.0 on Maven Central as soon as I find the time for it (and close this bug)
- If there are bugs, so be it. Someone will hopefully create a CVE instead of abusing it
- Matt tries to work on some of the TODOs on his Open Source Friday

**Comment by schildbach** [comment]
Sorry, I forgot the date. But good to see you came to the conclusion to release. (-:

**Comment by techguy613** [comment]
Thanks for the chat, Ingo! I hope all is well with you man :)

**Comment by ibauersachs** [comment]
Done.
