### ISSUE TITLE
mvn target to make a .jar library

### ISSUE THREAD

**Issue by ralfhauser** [ibauersachs/dnssecjava#10]
It would be great to have a target that builds a .jar file that can be used e.g. in an application running under tomcat

**Comment by ibauersachs** [comment]
The project is released on [Maven Central](https://search.maven.org/search?q=a:dnssecjava) if you want to download a .jar manually. If you want to build it yourself, execute `mvn package`.

**Comment by ralfhauser** [comment]
thx, found it as
   ./target/dnssecjava-1.1.4-SNAPSHOT.jar
