### ISSUE TITLE
java.naming.factory.initial ==> DnsSecContextFactory ?

### ISSUE THREAD

**Issue by ralfhauser** [ibauersachs/dnssecjava#12]
E.g. in badpenguin.dkim, the following approach to DNS lookup is used:

		Hashtable<String,String> env = new Hashtable<String,String>();	
		env.put("java.naming.factory.initial", "com.sun.jndi.dns.DnsContextFactory");
		env.put("java.naming.provider.url", "dns://" + nameServer );
		dnsCtx = new InitialDirContext(env);
                ...
		Attributes attrs = null;
		try {
			attrs = dnsCtx.getAttributes(lookup, new String[] {"txt"});
		} catch (NamingException e) {
                      ...

Could your code  be fit into something like 

    public class DnsSecContextFactory extends DnsContextFactory {
        ...

?

**Comment by ibauersachs** [comment]
I don't know the API of DnsContextFactory. But if this is still supported in Java 9+ then why not give it a go?

It might be a good idea to implement this as a separate project though to support any implementation of Dnsjava's Resolver interface. The suggested DnssecContextFactory would then simply be a specific implementation taking care of the initialization (setting options, key loading).

**Comment by ralfhauser** [comment]
see http://www.docjar.com/html/api/com/sun/jndi/dns/DnsContextFactory.java.html or https://github.com/frohoff/jdk8u-jdk/blob/master/src/share/classes/com/sun/jndi/dns/DnsContextFactory.java

**Comment by ibauersachs** [comment]
There's basically nothing to reuse in `DnsContextFactory` and it's in a private namespace that cannot be used in Java 9+.

A `DnssecContextFactory` doesn't make much sense to me, while a `DnsjavaContextFactory` could be useful. Which resolver type/class to use could be specified with a property in the env-Hashtable.

Implementing this would basically follow the [JNDI DNS specification](https://docs.oracle.com/javase/8/docs/technotes/guides/jndi/jndi-dns.html) and [API](https://docs.oracle.com/en/java/javase/11/docs/api/java.naming/javax/naming/spi/InitialContextFactory.html).
