### ISSUE TITLE
Very old log4j version

### ISSUE THREAD

**Issue by schildbach** [ibauersachs/dnssecjava#2]
I noticed dnssecjava is using a very old log4j version. And it depends on a all-in-one JAR which depends on a lot classes/API not available under Android. This causes all sorts of build and runtime issues. I suggest switching the dependency to:

```
<dependency>
  <groupId>org.apache.logging.log4j</groupId>
  <artifactId>log4j-api</artifactId>
  <version>2.5</version>
</dependency>
```

I assume the API hasn't changed much, so this is probably a drop-in replacement.

OR: Even better, use the more modern SLF4J:

```
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>1.7.18</version>
</dependency>
```

I can provide a PR for one of the options.

**Comment by ibauersachs** [comment]
Log4j v2 is incompatible with v1 (and requires Java 7). I'm fine with switching to SLF4J, can you create that PR please?

**Comment by schildbach** [comment]
Ah, you're right, 2.4+ requires Java7. We could use 2.3 however, it requires only Java6. But since you're fine with SLF4J I'll create a PR for that.

**Comment by schildbach** [comment]
How about #3?

**Comment by ibauersachs** [comment]
Merged. Is there something else you have coming up or do you want me to release this as v1.1?

**Comment by schildbach** [comment]
Thanks! I think there will perhaps be more coming, so no hurry for me. I'll try the snapshot.
