### ISSUE TITLE
Java 6/Java 7 compatible jar

### ISSUE THREAD

**Issue by fwiersENO** [ibauersachs/dnssecjava#20]
Thank you for this library, it is very useful in my case. One remark: the 1.2.0 jar from Maven central appears to be only suitable for Java 8 or higher version, despite the pom.xml from this project indicating Java 6 or higher.
I recompiled the 1.2.0 version using a modified pom (packaging set to "jar") and Java 8 - this does result in a jar-file that is at least compatible with Java 7 (I have not tested with Java 6).

**Comment by ibauersachs** [comment]
I didn't care about pre Java 8 anymore during the last release, sorry. The next release will probably reference dnsjava v3 which uses Java 8 features, so I'll close this as a won't fix.
