### ISSUE TITLE
Support more algorithms

### ISSUE THREAD

**Issue by hyperxpro** [ibauersachs/dnssecjava#21]
When will this library get support for Ed25519, Ed448 and GOST Algorithms?

**Comment by ibauersachs** [comment]
GOST has never been on my mind, is it actually used anywhere? The others, I can't give you an ETA, but I guess I should start working on them...

**Comment by hyperxpro** [comment]
> GOST has never been on my mind, is it actually used anywhere? There others, I can't give you an ETA, but I guess I should start working on them...

Yeah, I do agree GOST is not used widely but to make library compliant with standards, we gotta support them. My team is ready to validate and audit the library once everything is done. Can we work together on this?

**Comment by ibauersachs** [comment]
EdDSA requires support in dnsjava, and BouncyCastle. I've been working on that, but I don't know yet when I'll do a new release of dnsjava.
Still not sure about GOST, see [rfc8624#3.1](https://tools.ietf.org/html/rfc8624#section-3.1) which discourages it.

**Comment by hyperxpro** [comment]
> EdDSA requires support in dnsjava, and BouncyCastle. I've been working on that, but I don't know yet when I'll do a new release of dnsjava.
> Still not sure about GOST, see [rfc8624#3.1](https://tools.ietf.org/html/rfc8624#section-3.1) which discourages it.

Yeah, BouncyCastle is needed for EdDSA. 

I agree GOST is not widely used and nobody encourages to use it but to take library fully compliant with RFC I don't see other way. People using this library in their DNS Resolver will encounter problems if they get GOST Algorithm by some website DNS Server. Chances are less but still it can happen. I will be happy to add GOST support. Can you create new development branch so I can contribute to that?

**Comment by ibauersachs** [comment]
> I agree GOST is not widely used and nobody encourages to use it but to take library fully compliant with RFC I don't see other way. People using this library in their DNS Resolver will encounter problems if they get GOST Algorithm by some website DNS Server. Chances are less but still it can happen. I will be happy to add GOST support. Can you create new development branch so I can contribute to that?

Create a pull request...
