### ISSUE TITLE
TrustAnchorStore lookup method is case sensitive

### ISSUE THREAD

**Issue by GuillaumeBlanchet** [ibauersachs/dnssecjava#26]
Repo steps:
1. Initialize the following basic `trustAnchor` for the root and gallup TLD: 
```
.			0	IN	DS	19036 8 2 49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5
.			0	IN	DS	20326 8 2 E06D44B80B8F1D39A95C0B0D7C65D08458E880409BBC683457104237C7F8EC8D
GALLUP.			86400	IN	DS	34159 8 2 AE9BBA11562A260AAA062E2EB9881443044FDB8998B6A81C25D34D0D6BF49CB5
```
2. Then call 
```
validatingResolver
          .loadTrustAnchors(new ByteArrayInputStream(trustAnchor.toString().getBytes()))
```
3. Then send any dns query, say `GALLUP., type = DNSKEY, class = IN`

The response will contain the following bogus reason:

`Could not establish a chain of trust to keys for [.]. Reason: Missing DNSKEY RRset in response to DNSKEY query for ..`

Nevertheless gallup is in the chain of trust: https://dnssec-analyzer.verisignlabs.com/nic.gallup

This seems to be a bug in the TrustAnchorStore lookup method that compare the gallup key with GALLUP and fail to find it.

Thank you for this awesome lib by the way and best regards

**Comment by ibauersachs** [comment]
Thanks! I've pushed a fix to master and 2.1.0-SNAPSHOT is available on OSSRH (Maven Central Snapshots).
