### ISSUE TITLE
Throw an error (or indicate it) on timeout instead of logging

### ISSUE THREAD

**Issue by pgoggijr** [ibauersachs/dnssecjava#6]
I'd like to specifically handle timeout errors in my application.  

There doesn't seem to be any specific indication of a timeout error in the dns record (if there is please let me know!)

**Comment by ibauersachs** [comment]
No, there isn't anything. But from a DNSSEC point if view, it is impossible to distinguish a timeout from a deliberate faked no reply.
However, you should be able to handle timeouts within a custom resolver that you pass to the ValidatingResolver.
